show_configuration_security_address_book = """<rpc-reply xmlns:junos="http://xml.juniper.net/junos/23.4R2-S5.5/junos">
    <data>
    <configuration junos:commit-seconds="1776634460" junos:commit-localtime="2026-04-19 21:34:20 UTC" junos:commit-user="cs7_admin">
            <security>
                <address-book>
                    <name>global</name>
                    <address>
                        <name>server002.cs7networks.co.uk</name>
                        <ip-prefix>10.83.20.11/32</ip-prefix>
                    </address>        
                    <address>
                        <name>WIRELESS-01_subnet</name>
                        <ip-prefix>192.168.1.0/24</ip-prefix>
                    </address>
                    <address>           
                        <name>server002.cs7networks.co.uk-v6</name>
                        <ip-prefix>2001:270:6aaa:20::11/128</ip-prefix>
                    </address>
                    <address>
                        <name>firmware.grandstream.com</name>
                        <dns-name>
                            <name>firmware.grandstream.net</name>
                        </dns-name>
                    </address>
                </address-book>
            </security>
        </configuration>
    </data>
    <cli>
        <banner></banner>
    </cli>
</rpc-reply>"""

show_configuration_securiy_zones = """<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/23.4R2-S5.5/junos">
<data>
<configuration xmlns="http://xml.juniper.net/xnm/1.1/xnm" junos:commit-seconds="1776634460" junos:commit-localtime="2026-04-19 21:34:20 UTC" junos:commit-user="cs7_admin">
    <security>
        <zones>
            <security-zone>
                <name>OUTSIDE</name>
                <host-inbound-traffic>
                    <system-services>
                        <name>ping</name>
                    </system-services>
                    <system-services>
                        <name>ntp</name>
                    </system-services>
                    <system-services>
                        <name>bootp</name>
                    </system-services>
                    <system-services>
                        <name>dhcp</name>
                    </system-services>
                    <system-services>
                        <name>dhcpv6</name>
                    </system-services>
                </host-inbound-traffic>
                <interfaces>
                    <name>pt-1/0/0.0</name>
                </interfaces>
                <interfaces>
                    <name>pp0.0</name>
                </interfaces>
            </security-zone>
            <security-zone>
                <name>MGMT</name>
                <host-inbound-traffic>
                    <system-services>
                        <name>all</name>
                    </system-services>
                    <protocols>
                        <name>all</name>
                    </protocols>
                </host-inbound-traffic>
                <interfaces>
                    <name>irb.2</name>
                </interfaces>
            </security-zone>
            <security-zone>
                <name>WIRELESS_01</name>
                <host-inbound-traffic>
                    <system-services>
                        <name>all</name>
                    </system-services>
                    <protocols>
                        <name>all</name>
                    </protocols>
                </host-inbound-traffic>
                <interfaces>
                    <name>irb.30</name>
                    <host-inbound-traffic>
                        <system-services>
                            <name>snmp</name>
                        </system-services>
                        <system-services>
                            <name>dhcp</name>
                        </system-services>
                        <system-services>
                            <name>ssh</name>
                        </system-services>
                        <system-services>
                            <name>ping</name>
                        </system-services>
                    </host-inbound-traffic>
                </interfaces>
                <interfaces>
                    <name>irb.3</name>
                    <host-inbound-traffic>
                        <system-services>
                            <name>all</name>
                        </system-services>
                        <protocols>
                            <name>all</name>
                        </protocols>
                    </host-inbound-traffic>
                </interfaces>
            </security-zone>
        </zones>
    </security>
</configuration>
</data>
<cli>
        <banner></banner>
    </cli>
</rpc-reply>
"""

show_configuration_vlans = """<rpc-reply message-id="urn:uuid:b1878def-874b-4743-9153-c12972e786ea">
  <data>
    <configuration commit-seconds="1776634460" commit-localtime="2026-04-19 21:34:20 UTC" commit-user="cs7_admin">
      <vlans>
        <vlan>
          <name>IOT_01</name>
          <vlan-id>31</vlan-id>
          <l3-interface>irb.31</l3-interface>
        </vlan>
        <vlan>
          <name>MGMT</name>
          <vlan-id>2</vlan-id>
          <l3-interface>irb.2</l3-interface>
        </vlan>
        <vlan>
          <name>PROXMOX_NO_INTERNET</name>
          <vlan-id>15</vlan-id>
          <l3-interface>irb.15</l3-interface>
        </vlan>
      </vlans>
    </configuration>
  </data>
</rpc-reply>"""